import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { recognizeCreateTableCoreShape } from "../src/create-table-core-shape.js";
import { applyRawInputProfile } from "../src/input-profile.js";
import {
  UTF8_BOM,
  acceptText,
  columnExpressionSpan,
  concatenate,
  expectAccepted,
  expectAmbiguous,
  expectConflict,
  expectRecognized,
  expectRefused,
  expectUnbalanced,
  expectUnexpectedToken,
  recognizeText,
  spanText,
} from "./create-table-test-helpers.js";

const encoder = new TextEncoder();
describe("recognizeCreateTableCoreShape", () => {
  it("characterizes every current column-clause cardinality slot", () => {
    const cases = [
      { clauses: "NULL NOT NULL", labels: ["NULL", "NOT NULL"], anchor: "NOT" },
      {
        clauses: "PRIMARY KEY PRIMARY KEY",
        labels: ["PRIMARY KEY", "PRIMARY KEY"],
        anchor: "PRIMARY",
      },
      { clauses: "UNIQUE UNIQUE", labels: ["UNIQUE", "UNIQUE"], anchor: "UNIQUE" },
      {
        clauses: "CHECK (true) CHECK (false)",
        labels: ["CHECK", "CHECK"],
        anchor: "CHECK",
      },
      {
        clauses: "REFERENCES p(id) REFERENCES q(id)",
        labels: ["REFERENCES", "REFERENCES"],
        anchor: "REFERENCES",
      },
      { clauses: "DEFAULT 1 DEFAULT 2", labels: ["DEFAULT", "DEFAULT"], anchor: "DEFAULT" },
      {
        clauses: "GENERATED ALWAYS AS (1) STORED GENERATED ALWAYS AS (2) STORED",
        labels: ["GENERATED STORED", "GENERATED STORED"],
        anchor: "GENERATED",
      },
      {
        clauses: "GENERATED ALWAYS AS IDENTITY GENERATED BY DEFAULT AS IDENTITY",
        labels: ["IDENTITY", "IDENTITY"],
        anchor: "GENERATED",
      },
    ] as const;

    for (const testCase of cases) {
      const sourceText = `create table t (c int ${testCase.clauses})`;
      const input = acceptText(sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));

      assert.deepEqual(refusal.clauseLabels, testCase.labels, testCase.clauses);
      assert.equal(spanText(input, refusal.span), testCase.anchor, testCase.clauses);
      assert.equal(
        refusal.span.start.rawByteOffset,
        sourceText.lastIndexOf(testCase.anchor),
        testCase.clauses,
      );
    }
  });
  it("characterizes the declarative column-conflict pair table and accepted controls", () => {
    const conflictCases = [
      {
        type: "int",
        clauses: "NULL PRIMARY KEY",
        labels: ["NULL", "PRIMARY KEY"],
        anchor: "PRIMARY",
      },
      {
        type: "int",
        clauses: "PRIMARY KEY NULL",
        labels: ["PRIMARY KEY", "NULL"],
        anchor: "NULL",
      },
      {
        type: "int",
        clauses: "DEFAULT 1 GENERATED ALWAYS AS (2) STORED",
        labels: ["DEFAULT", "GENERATED STORED"],
        anchor: "GENERATED",
      },
      {
        type: "int",
        clauses: "GENERATED ALWAYS AS (1) STORED DEFAULT 2",
        labels: ["GENERATED STORED", "DEFAULT"],
        anchor: "DEFAULT",
      },
      { type: "serial", clauses: "NULL", labels: ["SERIAL", "NULL"], anchor: "NULL" },
      {
        type: "serial",
        clauses: "DEFAULT 1",
        labels: ["SERIAL", "DEFAULT"],
        anchor: "DEFAULT",
      },
      {
        type: "serial",
        clauses: "GENERATED ALWAYS AS (1) STORED",
        labels: ["SERIAL", "GENERATED STORED"],
        anchor: "GENERATED",
      },
      {
        type: "int",
        clauses: "NULL GENERATED ALWAYS AS IDENTITY",
        labels: ["NULL", "IDENTITY"],
        anchor: "GENERATED",
      },
      {
        type: "int",
        clauses: "DEFAULT 1 GENERATED ALWAYS AS IDENTITY",
        labels: ["DEFAULT", "IDENTITY"],
        anchor: "GENERATED",
      },
      {
        type: "int",
        clauses: "GENERATED ALWAYS AS (1) STORED GENERATED ALWAYS AS IDENTITY",
        labels: ["GENERATED STORED", "IDENTITY"],
        anchor: "GENERATED",
      },
      {
        type: "serial",
        clauses: "GENERATED ALWAYS AS IDENTITY",
        labels: ["SERIAL", "IDENTITY"],
        anchor: "GENERATED",
      },
    ] as const;

    for (const testCase of conflictCases) {
      const sourceText = `create table t (c ${testCase.type} ${testCase.clauses})`;
      const input = acceptText(sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));
      assert.deepEqual(refusal.clauseLabels, testCase.labels, sourceText);
      assert.equal(refusal.span.start.rawByteOffset, sourceText.lastIndexOf(testCase.anchor));
    }

    for (const clauses of [
      "NOT NULL PRIMARY KEY",
      "PRIMARY KEY NOT NULL",
      "NULL UNIQUE",
      "UNIQUE NULL",
      "CHECK (true) REFERENCES p(id)",
      "REFERENCES p(id) CHECK (true)",
      "DEFAULT 1 PRIMARY KEY",
      "PRIMARY KEY DEFAULT 1",
      "UNIQUE REFERENCES p(id)",
      "REFERENCES p(id) UNIQUE",
    ]) {
      expectRecognized(recognizeText(`create table t (c int ${clauses})`));
    }
  });
  it("selects duplicate table CHECK names relation-wide with quoted controls", () => {
    const ambiguousCases = [
      "create table t (a int, constraint dup check (true), constraint DUP check (false))",
      "create table t (a int constraint dup check (true), constraint DUP check (false))",
      "create table t (constraint dup check (true), a int, constraint DUP unique (a))",
      'create table t (a int, constraint dup check (true), constraint "dup" check (false))',
    ];

    for (const sourceText of ambiguousCases) {
      const input = acceptText(sourceText);
      const refusal = expectAmbiguous(recognizeCreateTableCoreShape(input));
      assert.equal(spanText(input, refusal.span).toLowerCase(), "constraint", sourceText);
      assert.equal(
        refusal.span.start.rawByteOffset,
        sourceText.toLowerCase().lastIndexOf("constraint"),
        sourceText,
      );
    }

    const distinct = expectRecognized(
      recognizeText(
        'create table t (a int, constraint dup check (true), constraint "Dup" check (true), check (false))',
      ),
    ).coreShape;
    assert.equal(distinct.derived.tableCheckConstraints.length, 3);
    assert.deepEqual(
      distinct.derived.explicitConstraintNames.map((occurrence) => occurrence.name.identity),
      ["dup", "Dup"],
    );
  });
  it("selects duplicate explicit names across scopes, forms, and source-order reversals", () => {
    const cases = [
      "create table t (a int constraint Dup null, b int constraint dup check (true))",
      "create table t (a int constraint dup unique, constraint DUP unique (a))",
      "create table t (constraint dup unique (a), a int constraint DUP check (true))",
      "create table t (a int constraint dup null, constraint dup primary key (a))",
      "create table t (a int constraint dup check (true) constraint dup check (false))",
    ];

    for (const sourceText of cases) {
      const input = acceptText(sourceText);
      const refusal = expectAmbiguous(recognizeCreateTableCoreShape(input));
      const first = sourceText.toLowerCase().indexOf("constraint");
      const second = sourceText.toLowerCase().indexOf("constraint", first + 1);
      assert.equal(refusal.span.start.rawByteOffset, second, sourceText);
      assert.equal(spanText(input, refusal.span).toLowerCase(), "constraint", sourceText);
    }

    expectRecognized(
      recognizeText(
        'create table t (a int constraint foo null, b int constraint "Foo" null, c int constraint "é" check (true), d int constraint "é" check (true))',
      ),
    );

    for (const sourceText of [
      'create table t (a int constraint foo null, b int constraint "foo" check (true))',
      'create table t (a int constraint "é" null, b int constraint "é" check (true))',
    ]) {
      const input = acceptText(sourceText);
      const refusal = expectAmbiguous(recognizeCreateTableCoreShape(input));
      assert.equal(spanText(input, refusal.span).toLowerCase(), "constraint");
      assert.equal(
        refusal.span.start.rawByteOffset,
        encoder.encode(sourceText.slice(0, sourceText.toLowerCase().lastIndexOf("constraint")))
          .byteLength,
      );
    }
  });
  it("centralizes table PRIMARY KEY and explicit NULL establishment ordering", () => {
    const cases = [
      {
        sourceText: "create table t (a int null, primary key (a))",
        labels: ["NULL", "PRIMARY KEY"],
        anchor: "primary",
        column: "a",
      },
      {
        sourceText: "create table t (primary key (a), a int null)",
        labels: ["PRIMARY KEY", "NULL"],
        anchor: "null",
        column: "a",
      },
      {
        sourceText: "create table t (b int null, a int null, primary key (a,b))",
        labels: ["NULL", "PRIMARY KEY"],
        anchor: "primary",
        column: "b",
      },
    ] as const;

    for (const testCase of cases) {
      const input = acceptText(testCase.sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));
      assert.deepEqual(refusal.clauseLabels, testCase.labels, testCase.sourceText);
      assert.equal(refusal.column.identity, testCase.column, testCase.sourceText);
      assert.equal(spanText(input, refusal.span).toLowerCase(), testCase.anchor);
    }

    const precedenceText = "create table t (a int null, b int primary key, primary key (a))";
    const precedenceInput = acceptText(precedenceText);
    const precedence = expectAmbiguous(recognizeCreateTableCoreShape(precedenceInput));
    assert.equal(spanText(precedenceInput, precedence.span).toLowerCase(), "primary");
    assert.equal(precedence.span.start.rawByteOffset, precedenceText.lastIndexOf("primary"));
  });
  it("filters repeated inline PRIMARY KEY before modeled-key ambiguity construction", () => {
    const repeatedText = "create table t (c int PRIMARY KEY PRIMARY KEY)";
    const repeatedInput = acceptText(repeatedText);
    const repeated = expectConflict(recognizeCreateTableCoreShape(repeatedInput));
    assert.deepEqual(repeated.clauseLabels, ["PRIMARY KEY", "PRIMARY KEY"]);
    assert.equal(spanText(repeatedInput, repeated.span), "PRIMARY");
    assert.equal(repeated.span.start.rawByteOffset, repeatedText.lastIndexOf("PRIMARY"));

    const cases = [
      "create table t (a int PRIMARY KEY, b int PRIMARY KEY)",
      "create table t (a int PRIMARY KEY, b int PRIMARY KEY, c int PRIMARY KEY)",
    ];

    for (const sourceText of cases) {
      const input = acceptText(sourceText);
      const refusal = expectAmbiguous(recognizeCreateTableCoreShape(input));
      const firstPrimary = sourceText.indexOf("PRIMARY");
      const secondPrimary = sourceText.indexOf("PRIMARY", firstPrimary + 1);
      assert.equal(spanText(input, refusal.span), "PRIMARY", sourceText);
      assert.equal(refusal.span.start.rawByteOffset, secondPrimary, sourceText);
    }
  });
  it("prefers a same-location PK ambiguity over its NULL conflict", () => {
    const sourceText = "create table t (a int PRIMARY KEY, b int NULL PRIMARY KEY)";
    const input = acceptText(sourceText);
    const refusal = expectAmbiguous(recognizeCreateTableCoreShape(input));

    assert.equal(spanText(input, refusal.span), "PRIMARY");
    assert.equal(refusal.span.start.rawByteOffset, sourceText.lastIndexOf("PRIMARY"));
  });
  it("models inline UNIQUE singleton lists by normalized column identity", () => {
    const repeatedText = "create table t (c int UNIQUE CHECK (true) UNIQUE)";
    const repeatedInput = acceptText(repeatedText);
    const repeated = expectConflict(recognizeCreateTableCoreShape(repeatedInput));
    assert.deepEqual(repeated.clauseLabels, ["UNIQUE", "UNIQUE"]);
    assert.equal(spanText(repeatedInput, repeated.span), "UNIQUE");
    assert.equal(repeated.span.start.rawByteOffset, repeatedText.lastIndexOf("UNIQUE"));

    const adjacentRepeatedText = "create table t (c int UNIQUE UNIQUE)";
    const adjacentRepeatedInput = acceptText(adjacentRepeatedText);
    const adjacentRepeated = expectConflict(recognizeCreateTableCoreShape(adjacentRepeatedInput));
    assert.deepEqual(adjacentRepeated.clauseLabels, ["UNIQUE", "UNIQUE"]);
    assert.equal(spanText(adjacentRepeatedInput, adjacentRepeated.span), "UNIQUE");
    assert.equal(
      adjacentRepeated.span.start.rawByteOffset,
      adjacentRepeatedText.lastIndexOf("UNIQUE"),
    );

    const distinct = expectRecognized(
      recognizeText('create table t (a int UNIQUE, b int UNIQUE, "é" int UNIQUE, "é" int UNIQUE)'),
    ).coreShape;
    assert.deepEqual(
      distinct.derived.columns.map((column) => [
        column.name.identity,
        column.clauseOccurrences.map(({ kind }) => kind),
      ]),
      [
        ["a", ["unique"]],
        ["b", ["unique"]],
        ["é", ["unique"]],
        ["é", ["unique"]],
      ],
    );

    const duplicateColumnText = "create table t (a int UNIQUE, a text UNIQUE)";
    const duplicateColumnInput = acceptText(duplicateColumnText);
    const duplicateColumn = expectAmbiguous(recognizeCreateTableCoreShape(duplicateColumnInput));
    assert.equal(spanText(duplicateColumnInput, duplicateColumn.span), "a");
    assert.equal(
      duplicateColumn.span.start.rawByteOffset,
      duplicateColumnText.lastIndexOf("a text"),
    );
  });
  it("retains explicit constraint-name evidence on an ineligible repeated inline key", () => {
    const sourceText = "create table t (c int constraint dup unique constraint DUP unique)";
    const input = acceptText(sourceText);
    const refusal = expectAmbiguous(recognizeCreateTableCoreShape(input));

    assert.equal(spanText(input, refusal.span), "constraint");
    assert.equal(refusal.span.start.rawByteOffset, sourceText.lastIndexOf("constraint"));
  });
  it("applies only the authority-defined PRIMARY KEY nullability conflict", () => {
    const conflictCases = [
      {
        clauses: "NULL PRIMARY KEY",
        type: "int",
        labels: ["NULL", "PRIMARY KEY"],
        anchor: "PRIMARY",
      },
      {
        clauses: "PRIMARY KEY NULL",
        type: "int",
        labels: ["PRIMARY KEY", "NULL"],
        anchor: "NULL",
      },
      {
        clauses: "PRIMARY KEY NULL",
        type: "serial",
        labels: ["PRIMARY KEY", "NULL"],
        anchor: "NULL",
      },
      {
        clauses: "NULL PRIMARY KEY",
        type: "serial",
        labels: ["SERIAL", "NULL"],
        anchor: "NULL",
      },
    ] as const;

    for (const testCase of conflictCases) {
      const sourceText = `create table t (c ${testCase.type} ${testCase.clauses})`;
      const input = acceptText(sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));
      assert.deepEqual(refusal.clauseLabels, testCase.labels, sourceText);
      assert.equal(spanText(input, refusal.span), testCase.anchor, sourceText);
      assert.equal(
        refusal.span.start.rawByteOffset,
        sourceText.indexOf(testCase.anchor),
        sourceText,
      );
    }

    for (const clauses of [
      "NOT NULL PRIMARY KEY",
      "PRIMARY KEY NOT NULL",
      "NULL UNIQUE",
      "UNIQUE NULL",
      "DEFAULT 1 CHECK (true) PRIMARY KEY UNIQUE",
      "UNIQUE PRIMARY KEY CHECK (true) DEFAULT 1",
    ]) {
      expectRecognized(recognizeText(`create table t (c int ${clauses})`));
    }

    for (const clauses of ["PRIMARY KEY", "UNIQUE", "PRIMARY KEY UNIQUE", "UNIQUE PRIMARY KEY"]) {
      expectRecognized(recognizeText(`create table t (c serial ${clauses})`));
    }
  });
  it("preserves lexical, structural, and grammar precedence around modeled key candidates", () => {
    for (const sourceText of [
      "create table t (c int UNIQUE E'open",
      "create table t (c int PRIMARY KEY UNIQUE E'open",
      "create table t (c int UNIQUE UNIQUE GENERATED E'open",
      "create table t (c int PRIMARY E'open",
      "create table t (c int CONSTRAINT named PRIMARY KEY E'open",
    ]) {
      const { refusal } = expectRefused(recognizeText(sourceText));
      assert.equal(refusal.refusalId, "unterminated_string", sourceText);
    }

    const structuralInput = acceptText("create table t (c int PRIMARY KEY PRIMARY KEY CHECK ([)]");
    assert.equal(
      spanText(structuralInput, expectUnbalanced(recognizeCreateTableCoreShape(structuralInput))),
      ")",
    );

    for (const testCase of [
      {
        sourceText: "create table t (c int PRIMARY WRONG E'open",
        boundary: "WRONG",
      },
    ]) {
      const input = acceptText(testCase.sourceText);
      assert.equal(
        spanText(input, expectUnexpectedToken(input, recognizeCreateTableCoreShape(input))),
        testCase.boundary,
        testCase.sourceText,
      );
    }
  });
  it("selects every repeated or mixed explicit-nullability conflict in source order", () => {
    const cases = [
      {
        clauses: "NULL CHECK (true) NULL",
        labels: ["NULL", "NULL"],
        anchor: "NULL",
      },
      {
        clauses: "NULL DEFAULT 1 NOT NULL",
        labels: ["NULL", "NOT NULL"],
        anchor: "NOT",
      },
      {
        clauses: "NOT NULL CHECK (true) NULL",
        labels: ["NOT NULL", "NULL"],
        anchor: "NULL",
      },
      {
        clauses: "NOT NULL DEFAULT 1 NOT NULL",
        labels: ["NOT NULL", "NOT NULL"],
        anchor: "NOT",
      },
    ] as const;

    for (const testCase of cases) {
      const sourceText = `create table t (c int ${testCase.clauses})`;
      const input = acceptText(sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));

      assert.deepEqual(refusal.clauseLabels, testCase.labels, testCase.clauses);
      assert.equal(spanText(input, refusal.span), testCase.anchor, testCase.clauses);
      assert.equal(
        refusal.span.start.rawByteOffset,
        sourceText.lastIndexOf(testCase.anchor),
        testCase.clauses,
      );
    }
  });
  it("applies exact serial shorthand interactions and establishment ordering", () => {
    for (const type of ["smallserial", "SeRiAl", "bigserial"]) {
      const sourceText = `create table t (c ${type} NULL)`;
      const input = acceptText(sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));
      assert.deepEqual(refusal.clauseLabels, ["SERIAL", "NULL"], type);
      assert.equal(spanText(input, refusal.span), "NULL", type);

      const required = expectRecognized(recognizeText(`create table t (c ${type} NOT NULL)`))
        .coreShape.derived.columns[0];
      assert.deepEqual(
        required?.clauseOccurrences.map(({ kind }) => kind),
        ["not_null"],
      );
    }

    for (const type of ['"serial"', "pg.serial", "serial(1)", "serial(1,2)", "serial[]"]) {
      const column = expectRecognized(recognizeText(`create table t (c ${type} NULL)`)).coreShape
        .derived.columns[0];
      assert.deepEqual(
        column?.clauseOccurrences.map(({ kind }) => kind),
        ["null"],
        type,
      );
    }

    for (const testCase of [
      {
        clauses: "DEFAULT 1 NULL",
        labels: ["SERIAL", "DEFAULT"],
        anchor: "DEFAULT",
      },
      { clauses: "NULL DEFAULT 1", labels: ["SERIAL", "NULL"], anchor: "NULL" },
      {
        clauses: "NOT NULL DEFAULT 1",
        labels: ["SERIAL", "DEFAULT"],
        anchor: "DEFAULT",
      },
    ] as const) {
      const sourceText = `create table t (c serial ${testCase.clauses})`;
      const input = acceptText(sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));
      assert.deepEqual(refusal.clauseLabels, testCase.labels, testCase.clauses);
      assert.equal(spanText(input, refusal.span), testCase.anchor, testCase.clauses);
    }
  });
  it("keeps nullability grammar failures lazy and post-parse conflicts deferred", () => {
    for (const testCase of [
      { sourceText: "create table t (c int NOT TRUE)", boundary: "TRUE" },
      { sourceText: "create table t (c int NOT)", boundary: ")" },
      { sourceText: 'create table t (c int "NULL")', boundary: '"NULL"' },
      {
        sourceText: "create table t (c int NULL NOT TRUE E'open",
        boundary: "TRUE",
      },
    ]) {
      const input = acceptText(testCase.sourceText);
      assert.equal(
        spanText(input, expectUnexpectedToken(input, recognizeCreateTableCoreShape(input))),
        testCase.boundary,
        testCase.sourceText,
      );
    }

    const lexical = expectRefused(recognizeText("create table t (c int NULL NULL NOT E'open"));
    assert.equal(lexical.refusal.refusalId, "unterminated_string");

    const structuralInput = acceptText("create table t (c int NULL NULL CHECK ([)]");
    assert.equal(
      spanText(structuralInput, expectUnbalanced(recognizeCreateTableCoreShape(structuralInput))),
      ")",
    );
  });
  it("selects nullability conflicts and duplicate-column ambiguity by establishment order", () => {
    const ambiguity = expectAmbiguous(
      recognizeText("create table t (a int, a int NULL CHECK (true) NULL)"),
    );
    assert.equal(ambiguity.refusalId, "ambiguous_declaration");

    const conflict = expectConflict(
      recognizeText("create table t (a int NULL DEFAULT 1 NULL, b int, b text)"),
    );
    assert.equal(conflict.column.identity, "a");
    assert.deepEqual(conflict.clauseLabels, ["NULL", "NULL"]);
  });
  it("selects repeated DEFAULT conflicts only after complete grammar consumption", () => {
    const sourceText = [
      "create table t (",
      "  \"é\" text DEFAULT 'first' CHECK (true) DEFAULT E'second'::text",
      ");",
    ].join("\r\n");
    const input = acceptText(sourceText);
    const { refusal } = expectRefused(recognizeCreateTableCoreShape(input));
    if (refusal.refusalId !== "conflicting_column_declaration") {
      assert.fail(`Expected DEFAULT conflict, received ${refusal.refusalId}`);
    }

    assert.equal(refusal.column.identity, "é");
    assert.equal(refusal.column.quoted, true);
    assert.deepEqual(refusal.clauseLabels, ["DEFAULT", "DEFAULT"]);
    assert.equal(spanText(input, refusal.span), "DEFAULT");
    assert.equal(refusal.span.start.line, 2);
    assert.equal(refusal.span.start.column, 41);

    const lexicalWins = expectRefused(
      recognizeText("create table t (c int DEFAULT 1 DEFAULT 2, d text DEFAULT E'open"),
    );
    assert.equal(lexicalWins.refusal.refusalId, "unterminated_string");

    const malformedSecond = expectRefused(
      recognizeText("create table t (c int DEFAULT 1 DEFAULT fn([ 'open"),
    );
    assert.equal(malformedSecond.refusal.refusalId, "unterminated_string");

    const grammarWinsInput = acceptText("create table t (c int DEFAULT 1 DEFAULT 2 + 'open");
    assert.equal(
      spanText(
        grammarWinsInput,
        expectUnexpectedToken(grammarWinsInput, recognizeCreateTableCoreShape(grammarWinsInput)),
      ),
      "+",
    );
  });
  it("selects repeated CHECK conflicts from complete source-ordered occurrences", () => {
    const sourceText = [
      "CREATE TABLE t (",
      '  "é" int CHECK ("😀") DEFAULT 1 CHECK ("é")',
      ");",
    ].join("\r\n");
    const input = expectAccepted(
      applyRawInputProfile(concatenate(UTF8_BOM, encoder.encode(sourceText))),
    );
    const refusal = expectConflict(recognizeCreateTableCoreShape(input));
    const laterCheckOffset = sourceText.lastIndexOf("CHECK");
    const lineStart = sourceText.lastIndexOf("\n", laterCheckOffset) + 1;

    assert.equal(refusal.column.identity, "é");
    assert.equal(refusal.column.quoted, true);
    assert.deepEqual(refusal.clauseLabels, ["CHECK", "CHECK"]);
    assert.equal(spanText(input, refusal.span), "CHECK");
    assert.equal(
      refusal.span.start.rawByteOffset,
      UTF8_BOM.byteLength + encoder.encode(sourceText.slice(0, laterCheckOffset)).byteLength,
    );
    assert.equal(refusal.span.start.line, 2);
    assert.equal(
      refusal.span.start.column,
      Array.from(sourceText.slice(lineStart, laterCheckOffset)).length + 1,
    );

    const malformedRepeat = expectRefused(
      recognizeText("create table t (c int CHECK (true) CHECK ([ E'open"),
    );
    assert.equal(malformedRepeat.refusal.refusalId, "unterminated_string");
  });
  it("selects the earliest established clause conflict across kinds and columns", () => {
    const cases = [
      {
        sourceText: "create table t (a int DEFAULT 1 CHECK (true) DEFAULT 2 CHECK (false), b int)",
        labels: ["DEFAULT", "DEFAULT"],
      },
      {
        sourceText: "create table t (a int CHECK (true) DEFAULT 1 CHECK (false) DEFAULT 2, b int)",
        labels: ["CHECK", "CHECK"],
      },
      {
        sourceText: "create table t (a int CHECK (true) CHECK (false), b int DEFAULT 1 DEFAULT 2)",
        labels: ["CHECK", "CHECK"],
      },
    ] as const;

    for (const testCase of cases) {
      const input = acceptText(testCase.sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));
      assert.deepEqual(refusal.clauseLabels, testCase.labels, testCase.sourceText);
      assert.equal(
        refusal.span.start.rawByteOffset,
        testCase.sourceText.indexOf(
          testCase.labels[0],
          testCase.sourceText.indexOf(testCase.labels[0]) + 1,
        ),
        testCase.sourceText,
      );
    }
  });
  it("keeps an earlier clause conflict ahead of later column ambiguity", () => {
    for (const testCase of [
      {
        sourceText: "create table t (a int CHECK (true) CHECK (false), b int, b text)",
        labels: ["CHECK", "CHECK"],
      },
      {
        sourceText: "create table t (a int DEFAULT 1 DEFAULT 2, b int, b text)",
        labels: ["DEFAULT", "DEFAULT"],
      },
    ] as const) {
      const refusal = expectConflict(recognizeText(testCase.sourceText));
      assert.deepEqual(refusal.clauseLabels, testCase.labels);
      assert.equal(refusal.column.identity, "a");
    }
  });
  it("detects duplicate normalized target columns without treating quoting as identity", () => {
    const duplicateCases = [
      { sourceText: "create table t (Foo int, foo text)", later: "foo" },
      { sourceText: 'create table t (foo int, "foo" text)', later: '"foo"' },
      { sourceText: 'create table t ("é" int, "é" text)', later: '"é"' },
    ];

    for (const testCase of duplicateCases) {
      const input = acceptText(testCase.sourceText);
      const refusal = expectAmbiguous(recognizeCreateTableCoreShape(input));
      assert.equal(spanText(input, refusal.span), testCase.later, testCase.sourceText);
      assert.equal(
        refusal.span.start.rawByteOffset,
        encoder.encode(
          testCase.sourceText.slice(0, testCase.sourceText.lastIndexOf(testCase.later)),
        ).byteLength,
      );
      assert.deepEqual(Object.keys(refusal).sort(), ["refusalId", "span"]);
    }

    const control = expectRecognized(
      recognizeText('create table t (foo int, "FOO" text, "Foo" bigint)'),
    ).coreShape;
    assert.deepEqual(
      control.derived.columns.map((column) => column.name.identity),
      ["foo", "FOO", "Foo"],
    );

    const ambiguityFirstText = 'create table t ("é" int, "é" text, d int DEFAULT 1 DEFAULT 2)';
    const ambiguityFirst = acceptText(ambiguityFirstText);
    const refusal = expectAmbiguous(recognizeCreateTableCoreShape(ambiguityFirst));
    assert.equal(spanText(ambiguityFirst, refusal.span), '"é"');
    assert.equal(
      refusal.span.start.rawByteOffset,
      encoder.encode(ambiguityFirstText.slice(0, ambiguityFirstText.lastIndexOf('"é"'))).byteLength,
    );
  });
  it("recognizes only exact structural serial shorthand for DEFAULT conflicts", () => {
    for (const type of ["smallserial", "SeRiAl", "bigserial"]) {
      const sourceText = `create table t (c ${type} DEFAULT 1)`;
      const input = acceptText(sourceText);
      const refusal = expectConflict(recognizeCreateTableCoreShape(input));
      assert.deepEqual(refusal.clauseLabels, ["SERIAL", "DEFAULT"], type);
      assert.equal(spanText(input, refusal.span), "DEFAULT", type);
    }

    for (const type of ['"serial"', "pg.serial", "serial(1)", "serial(1,2)", "serial[]"]) {
      const sourceText = `create table t (c ${type} DEFAULT 1)`;
      const column = expectRecognized(recognizeText(sourceText)).coreShape.derived.columns[0];
      assert.equal(columnExpressionSpan(column, "default") === null, false, type);
    }
  });
  it("lets demanded parse failures outrank declaration candidates", () => {
    const lexical = expectRefused(
      recognizeText("create table t (a int, a text, b int DEFAULT E'open"),
    );
    assert.equal(lexical.refusal.refusalId, "unterminated_string");

    const structuralInput = acceptText(
      "create table t (a int DEFAULT 1 DEFAULT 2, b int CHECK ([)]",
    );
    assert.equal(
      spanText(structuralInput, expectUnbalanced(recognizeCreateTableCoreShape(structuralInput))),
      ")",
    );

    for (const testCase of [
      {
        sourceText: "create table t (a int DEFAULT 1 DEFAULT 2 COLLATE parent)",
        boundary: "COLLATE",
      },
      {
        sourceText: "create table t (a int CHECK (true) CHECK (false)); SELECT 1",
        boundary: "SELECT",
      },
    ]) {
      const input = acceptText(testCase.sourceText);
      assert.equal(
        spanText(input, expectUnexpectedToken(input, recognizeCreateTableCoreShape(input))),
        testCase.boundary,
      );
    }
  });
});
